'use server';

/**
 * @fileOverview Analyzes an image to determine the likelihood of it being a deepfake.
 *
 * - analyzeImageDeepfake - A function that handles the image deepfake analysis process.
 * - AnalyzeImageDeepfakeInput - The input type for the analyzeImageDeepfake function.
 * - AnalyzeImageDeepfakeOutput - The return type for the analyzeImageDeepfake function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'zod';

const AnalyzeImageDeepfakeInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo to be analyzed, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type AnalyzeImageDeepfakeInput = z.infer<typeof AnalyzeImageDeepfakeInputSchema>;

const AnalyzeImageDeepfakeOutputSchema = z.object({
  isDeepfake: z.boolean().describe('Whether or not the image is likely a deepfake or AI-generated.'),
  confidenceScore: z
    .number()
    .describe('A score between 0 and 1 indicating the confidence in the determination (1 being most confident).'),
  explanation: z.string().describe('A detailed, evidence-based explanation for the determination, citing specific visual artifacts, inconsistencies, or hallmarks of AI generation.'),
  relatedArticles: z.array(z.object({
    title: z.string().describe('The title of the related article.'),
    url: z.string().url().describe('The URL of the related article.'),
    source: z.string().describe('The name of the news source or publication.'),
  })).describe('A list of related articles from verified news sources that provide context or evidence for the analysis.'),
});
export type AnalyzeImageDeepfakeOutput = z.infer<typeof AnalyzeImageDeepfakeOutputSchema>;

export async function analyzeImageDeepfake(input: AnalyzeImageDeepfakeInput): Promise<AnalyzeImageDeepfakeOutput> {
  return analyzeImageDeepfakeFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeImageDeepfakePrompt',
  input: {schema: AnalyzeImageDeepfakeInputSchema},
  output: {schema: AnalyzeImageDeepfakeOutputSchema},
  prompt: `**Crucial Instruction: You have access to a search tool. Use it to find the most current information to verify the context and content of the image. Your analysis MUST be based on real-world events, figures, and data up to the present moment.**

You are a world-class digital forensics expert specializing in the detection of deepfakes and AI-generated images. Your analysis must be meticulous, grounded in the most current knowledge, and backed by verifiable sources found via search.

Analyze the provided image to determine if it has been digitally altered, manipulated, or entirely generated by AI.

- Determine if the image is a deepfake or AI-generated.
- Provide a confidence score for your determination (from 0 to 1).
- Deliver a detailed, evidence-based explanation. Reference specific visual artifacts, inconsistencies (e.g., in lighting, shadows, reflections, anatomy, background details), or hallmarks of known AI models.
- Use the search tool to cross-reference the image content with recent real-world events to assess its plausibility.
- Use the search tool to find and provide a list of up to 3 related articles from verified, reputable news portals (e.g., Reuters, Associated Press, BBC, major national newspapers) that provide context, fact-check the image, or discuss related events.

Image: {{media url=photoDataUri}}

Output your findings in JSON format.`,
});

const analyzeImageDeepfakeFlow = ai.defineFlow(
  {
    name: 'analyzeImageDeepfakeFlow',
    inputSchema: AnalyzeImageDeepfakeInputSchema,
    outputSchema: AnalyzeImageDeepfakeOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
